2025-03-31T23:12:49.001535+00:00 CRITICAL 'ansible_navigator.actions.run_playbook._handle_message' Unhandled message from runner queue, discarded: {'event': 'verbose', 'uuid': '8bf732ae-3d4d-43da-a6a9-fa62a6fdd6f0', 'counter': 1, 'stdout': '\x1b[0;34mUsing /etc/ansible/ansible.cfg as config file\x1b[0m', 'start_line': 0, 'end_line': 1, 'runner_ident': '4929347d-3c0a-44b3-97bc-5ffd4c33a29c', 'created': '2025-03-31T23:12:48.997556+00:00'}
2025-03-31T23:12:49.002271+00:00 CRITICAL 'ansible_navigator.actions.run_playbook._handle_message' Unhandled message from runner queue, discarded: {'event': 'verbose', 'uuid': '5e327e83-cc7a-402d-bd0d-ac482db87369', 'counter': 2, 'stdout': '\x1b[0;31mERROR! the playbook: feed.yml could not be found\x1b[0m', 'start_line': 1, 'end_line': 2, 'runner_ident': '4929347d-3c0a-44b3-97bc-5ffd4c33a29c', 'created': '2025-03-31T23:12:48.997881+00:00'}
2025-03-31T23:12:49.215556+00:00 ERROR 'ansible_navigator.actions.run_playbook.write_artifact' Saving the artifact file failed, resulted in the following error: f[Errno 13] Permission denied: '/feed-artifact-2025-03-31T23:12:49.213870+00:00.json'
